defaults: &defaults
  working_directory: ~/repo
  docker:
  - image: circleci/node:10.8.0

version: 2
jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "web/package.json" }}
        - v1-dependencies-
    - run: yarn install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "web/package.json" }}
    - run: yarn lint

workflows:
  version: 2
  build:
    jobs:
    - build
